---
- name: ensure nginx is installed
  apt: 
    name: nginx


- name: change TO default
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx


- name: Nginx enabled and started
  service:
    name: nginx
    state: started
    enabled: yes