---
- name: Install packages influxdb, influxdb-client
  apt:
    name: 
      - influxdb-client
      - influxdb
      - fping
    state: present

- name: InfluxDB enabled and started
  service:
    name: influxdb
    state: started
    enabled: yes
