---

- name: GATHERING FACTS 
  hosts: all
  roles: 
    - init
  become: yes


- name: BIND CONFIGS 
  hosts: dns_servers
  roles: 
    - bind9
  become: yes


- name: MYSQL CONFIGS 
  hosts:  db_servers
  roles:
    - mysql-lab11
    - mysql_exporter
  become: yes
  tags: 
    - mysql


- name: AGAMA CONFIGS 
  hosts: app_servers 
  roles: 
    - agama-lab4
  become: yes


- name: BACKUP CONFIGS
  hosts: all
  roles: 
    - backup
  become: yes


- name: GRAFANA CONFIGS
  hosts: grafana
  roles:
    - grafana
    - reverse
  become: yes
  tags: -grafana


- name: PROMETHEUS CONFIGS
  hosts: prometheus
  roles:
    - prometheus
  become: yes