---
- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: rndc reload
  become: yes
  become_user: root
  shell: rndc reload

- name: systemctl stop systemd-resolved
  become: yes
  become_user: root
  shell: systemctl stop systemd-resolved