---
  - name: Linux user juri
    user:
      name: juri
      
  - name: Linux user roman
    user:
      name: roman

  - name: Set authorized key taken from url for user juri
    authorized_key:
      user: juri
      state: present
      key: https://github.com/hudolejev.keys
        
  - name: Set authorized key taken from url for user roman
    authorized_key:
      user: roman
      state: present
      key: https://github.com/romankuchin.keys
