---

- name: Docker packages installation 
  apt:
    name: docker.io, python3-docker
    state: present

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Grafana directory
  file:
    name: /opt/docker/grafana
    state: directory
    owner: "472"
    group: "472"
    recurse: true

- name: Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    env:
      GF_SERVER_ROOT_URL: http://localhost:3000/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    ports:
      - 3001:3000
    volumes:
      - /opt/docker/grafana:/var/lib/grafana

- name: Change nginx reverse proxy 
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-enabled/default 
  notify: restart nginx


