---
  - name: install uWSGI
    apt:
      pkg: 
        - uwsgi
        - uwsgi-plugin-python3
        - python3-pymysql
      update_cache: yes


  - name: start uwsgi
    service:
      name: uwsgi
      state: started
      enabled: yes
    become: yes
   

  - name: copy agama.ini
    template:
      src: ../templates/agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
    notify: Restart uwsgi


