---
- name: Docker packages installation 
  apt:
    name: docker.io, python3-docker
    state: present

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Create agama directory 
  file:
    name: /opt/agama
    state: directory
    owner: "472"
    group: "472"
    recurse: true

- name: download Agama configs 
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/
    mode: "0644"

  
- name: create Docker image 
  docker_image:
    name: agama
    path: /opt/agama
    state: present


- name: Agama container
  docker_container:
    name: agama
    image: agama
    ports:
      - 8010:8000
    env:
      AGAMA_DATABASE_URI: mysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}


- name: Agama container num2
  docker_container:
    name: agama-1
    image: agama
    ports:
      - 8011:8000
    env:
      AGAMA_DATABASE_URI: mysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}