---
- name: Replace backup user (system)
  replace:
    path: /etc/passwd
    regexp: "^backup:x:34:34:backup:.+$"
    replace: backupoldone:x:34:34:backup:/var/backups:/bin/bash

- name: Create user backup
  user: 
    name: backup
    shell: /bin/bash
    createhome: yes
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
    state: present
  when: inventory_hostname in groups['dns_slaves']
  

- name: Create user backup
  user: 
    name: backup
    shell: /bin/bash
    createhome: yes
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
    state: present
    groups: grafana, prometheus, influxdb
  when: inventory_hostname in groups['dns_masters']
  