---

- name: Add the user 'backup' with a specific uid and a primary group of 'admin'
  user:
    name: backup
    password: "{{ password }}"
    create_home: True
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

  