---

# - name: Create a user on localhost with privileges
#   community.general.influxdb_user:
#     user_name: backup
#     user_password: "{{ backup_mysql_password }}"
#     login_username: "backup"
#     login_password: "{{ backup_mysql_password }}"
#     grants:
#       - database: 'telegraf'
#         privilege: 'READ'
#       - database: 'latency'
#         privilege: 'READ'


# - name: Store password
#   template:
#     src: .my.cnf.j2
#     dest: /home/backup/.my.cnf

- name: Add folder backup
  file:
    path: ~/backup
    state: directory
  become_user: backup


- name: Add folder restore
  file:
    path: ~/restore
    state: directory
  become_user: backup


- name: Add folder scripts
  file:
    path: ~/scripts
    state: directory
  become_user: backup


- name: Install duplicity
  apt:
    name: duplicity


- name: Sunday script
  template:
    src: sunday.sh.j2
    dest: /home/backup/scripts/sunday.sh
    mode: u=xrw,g=r,o=r
    owner: backup
  become_user: backup
  

- name: Everyday script
  template:
    src: everyday.sh.j2
    dest: /home/backup/scripts/everyday.sh
    mode: u=xrw,g=r,o=r
    owner: backup
  become_user: backup


- name: Cron configurations
  template:
    src: backup.j2
    dest: /etc/cron.d/backup


- name: Change grafana file permissions
  file:
    path: /var/lib/grafana/grafana.db
    mode: u=rw,g=r,o=r