---

- name: Add user 'backup' to group 'grafana'
  user:
    name: backup
    groups: 
       - admin
       - grafana



- name: Add folder backup
  file:
    path: ~/backup
    state: directory
  become_user: backup


- name: Add folder restore
  file:
    path: ~/restore
    state: directory
  become_user: backup
  

- name: Install duplicity
  apt:
    name: duplicity
    update_cache: yes
