---

 - name: Install mysql-server
   apt:
      name: 
         - mysql-server
         - python3-pymysql
      update_cache: yes
 
 
 - name: Change default port
   template:
      src: mysql_default
      dest: /etc/mysql/mysql.conf.d/override.cnf
   notify:
      - Systemctl
      - Restart mysql
   become: yes


 - name: MySQL database
   mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock


 - name: Create a MySQL user for the web application
   mysql_user:
      name: "{{mysql_user}}"
      password: "{{mysql_password}}"
      priv: "{{ mysql_database }}.*:ALL"
      host: "%"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock


 - name: Create a REPLICATION for lab11
   mysql_user:
      name: "replication"
      password: "{{mysql_password}}"
      host: "%"
      priv: "*.*:REPLICATION SLAVE"
      login_unix_socket: /var/run/mysqld/mysqld.sock
