---
- name: Install Node Exporters packages
  yum:
    name:
      - prometheus-node-exporter
    update_cache: yes

- name: Ensure node exporter is started and enabled
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
