---

- name: Add the user 'prometheus' with a specific uid and a primary group of 'admin'
  user:
    name: prometheus
    comment: user for bind exporter
    group: admin
  when: inventory_hostname in groups['dns_slaves']


- name: Package Bind Exporter
  apt: 
    name: prometheus-bind-exporter 


- name: Bind Enabled
  service: 
    name: prometheus-bind-exporter 
    state: started
    enabled: yes


