---

- name: Install Keepalived
  apt:
    name: keepalived


- name: Configure Keepalived
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: 
    - Restart keepalived 
  

- name: Keepalived enabled and started
  service:
    name: keepalived
    state: started
    enabled: yes