---
- name: install prometheus
  apt: 
    name: prometheus

- name: Prometheus enabled and started
  service:
    name: prometheus
    state: started
    enabled: yes

- name: add default ARGS
  template:
    src: ../templates/prometheus
    dest:  /etc/default/prometheus
  notify: 
    - restart prometheus

- name: changing yaml file in prometheus
  template:
    src: ../templates/prometheus.yaml.j2
    dest:  /etc/prometheus/prometheus.yml
  notify: 
    - restart prometheus