---
- name: install prometheus
  apt: 
    name: prometheus

- name: Nginx config for nodes
  template:
    src: ../templates/node_exporter
    dest:  /etc/nginx/sites-enabled/default
  notify: 
     - restart nginx

- name: add default ARGS
  template:
    src: ../templates/prometheus
    dest:  /etc/default/prometheus
  notify: 
    - restart prometheus

- name: changing yaml file in prometheus
  template:
    src: ../templates/prometheus.yaml.j2
    dest:  /etc/prometheus/prometheus.yml
  notify: 
    - restart prometheus