 - name: systemctl stop systemd-resolved
   become: yes
   become_user: root
   shell: systemctl stop systemd-resolved


 - name: Update your VMs DNS settings
   template:
      src: ../templates/resolv.conf
      dest: /etc/resolv.conf