---

- name: Docker packages installation 
  apt:
    name: docker.io, python3-docker
    state: present

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes



# - name: Change nginx reverse proxy 
#   template:
#     src: nginx_default.j2
#     dest: /etc/nginx/sites-enabled/default 
#   notify: restart nginx


