---
- name: Install prometheus nodes on all machines
  hosts: all 
  roles: 
    - node_exporter
  become: yes

- name: Install and configure Prometheus
  hosts: prometheus 
  roles: 
    - prometheus
  become: yes

