---

- name: Database server
  hosts: db_servers
  roles:
    - mysql-lab4
  become: yes
    

- name: Web app
  hosts: app_servers
  roles:
    - agama-lab4
    - uwsgi-lab4
    - nginx-lab4
  become: yes
  

