---

- name: Installing bind9 packages
  apt:
    name: 
      - bind9
      - python3-dnspython
    update_cache: yes


- name: Bind config
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9


- name: Bind zone config
  template:
    src: ../templates/named.conf.local
    dest: /etc/bind/named.conf.local 
  notify: restart bind9
  when: inventory_hostname in groups['dns_masters']


- name: Bind slave zone config
  template:
    src: ../templates/named.conf.local.slave.j2
    dest: /etc/bind/named.conf.local 
  notify: restart bind9
  when: inventory_hostname in groups['dns_slaves']


- name: Configure DNS zone
  template: 
    src: ../templates/db.aleke.kz.j2
    dest: /var/lib/bind/db.aleke.kz
    force: yes
  notify: restart bind9
  when: inventory_hostname in groups['dns_masters']



- name: Update your VMs DNS settings
  template:
    src: ../templates/resolv.conf
    dest: /etc/resolv.conf
  notify: 
      - service
      - restart bind9  
      - rndc reload
      - systemctl stop systemd-resolved


- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers


- name: Bind started and enabled
  service: 
    name: bind9
    state: started
    enabled: yes
    

# - name: Add bake record
#   nsupdate:
#     key_name: "update_secret"
#     key_secret: "{{dns_update_secret}}"
#     key_algorithm: "hmac-sha256"
#     server: "{{hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address']}}"
#     zone: "{{domain}}"
#     record: "aleke"
#     value: "192.168.42.120"
#     # ttl: 60
#   when: inventory_hostname == groups['dns_masters'][0]
#   # notify: restart bind9
