---
- name: Telegraf package download
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.16.0-1_amd64.deb
    dest: /opt/telegraf_1.16.0-1_amd64.deb


- name: Telegraf package installation
  apt: 
    deb: /opt/telegraf_1.16.0-1_amd64.deb


- name: Telegraf configuration
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: 
    - Restart Telegraf


- name: Telegraf enabled and started
  service:
    name: telegraf
    state: started
    enabled: yes
