---

- name: Setup
  hosts: all 
  become: yes
  roles:
    - init

- name: Bind exporter
  hosts: dns_servers 
  become: yes
  roles:
    - bind_exporter
  tags: 
    - bind


- name: MySQL exporter
  hosts: mysql_servers 
  become: yes
  roles:
    - mysql_exporter
  tags: 
    - mysql
  
- name: Nginx exporter
  hosts: web_servers
  become: yes
  roles:
    - nginx_exporter
  tags: 
    - nginx

- name: Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags: 
    - grafana
    
    